In [22]:
import pandas as pd
import ast

In [23]:
df1 = pd.read_csv('authors_data.csv')
df2 = pd.read_csv('works_ids.csv')
df3 = pd.read_csv('works_titles_abstracts.csv')
df4 = pd.read_csv('co_authors_data.csv')
df5 = pd.read_csv('co_authors_works.csv')
df6 = pd.read_csv('co_authors_works_titles_abstracts.csv')

In [24]:
authors_dataset = pd.concat([df1, df4], ignore_index=True)
papers_dataset = pd.concat([df2,df5], ignore_index = True)
abstracts_dataset = pd.concat([df3,df6],ignore_index = True)

In [32]:

authors_dataset = authors_dataset.drop_duplicates(subset = "author_id")
authors_dataset

,display_name,works_count,author_id,works_api_url,h_index,country_code
0,Étienne Ollion,131,https://openalex.org/A5022704573,https://api.openalex.org/works?filter=author.i...,17,NaN
1,Émilien Schultz,114,https://openalex.org/A5079294298,https://api.openalex.org/works?filter=author.i...,11,FR
2,Miriam Schirmer,13,https://openalex.org/A5036764962,https://api.openalex.org/works?filter=author.i...,3,NaN
3,Julia Mendelsohn,23,https://openalex.org/A5038833789,https://api.openalex.org/works?filter=author.i...,9,US
4,Dustin E. Wright,25,https://openalex.org/A5090577017,https://api.openalex.org/works?filter=author.i...,9,NaN
...,...,...,...,...,...,...
11264,Richard P. Larrick,132,https://openalex.org/A5017593408,https://api.openalex.org/works?filter=author.i...,42,US
11266,Laura J. Corbin,98,https://openalex.org/A5075431039,https://api.openalex.org/works?filter=author.i...,21,GB
11268,Ines Spielvogel,21,https://openalex.org/A5037745332,https://api.openalex.org/works?filter=author.i...,7,AT
11269,Engin Bozdag,17,https://openalex.org/A5081271375,https://api.openalex.org/works?filter=author.i...,8,US
11270,Jeffrey Reminga,12,https://openalex.org/A5075426054,https://api.openalex.org/works?filter=author.i...,8,NaN

In [29]:
papers_dataset = papers_dataset.drop_duplicates(subset = "id")
papers_dataset

,id,publication_year,cited_by_count,author_ids
0,https://openalex.org/W1999649023,1988.0,10484,"[https://openalex.org/A5110328496, https://ope..."
1,https://openalex.org/W2055957857,1999.0,3184,[https://openalex.org/A5064753440]
2,https://openalex.org/W3121315632,2011.0,2939,"[https://openalex.org/A5102851815, https://ope..."
3,https://openalex.org/W2002781392,2006.0,2510,"[https://openalex.org/A5064753440, https://ope..."
4,https://openalex.org/W2885869279,2018.0,2279,"[https://openalex.org/A5051345115, https://ope..."
...,...,...,...,...
81012,https://openalex.org/W4229711519,1995.0,21,[https://openalex.org/A5017593408]
81013,https://openalex.org/W4244918428,1998.0,11,[https://openalex.org/A5017593408]
81014,https://openalex.org/W4245271589,2004.0,310,[https://openalex.org/A5017593408]
81015,https://openalex.org/W2249172038,2012.0,27,[https://openalex.org/A5017593408]
81016,https://openalex.org/W4386888655,2023.0,13,[https://openalex.org/A5017593408]

In [26]:
papers_dataset["author_ids"] = papers_dataset["author_ids"].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)
several_authors_paper_dataset = papers_dataset[
    papers_dataset["author_ids"].str.len() >= 2
]
several_authors_paper_dataset

,id,publication_year,cited_by_count,author_ids
0,https://openalex.org/W1999649023,1988.0,10484,"[https://openalex.org/A5110328496, https://ope..."
2,https://openalex.org/W3121315632,2011.0,2939,"[https://openalex.org/A5102851815, https://ope..."
3,https://openalex.org/W2002781392,2006.0,2510,"[https://openalex.org/A5064753440, https://ope..."
4,https://openalex.org/W2885869279,2018.0,2279,"[https://openalex.org/A5051345115, https://ope..."
5,https://openalex.org/W2147453867,2006.0,2126,"[https://openalex.org/A5058815871, https://ope..."
...,...,...,...,...
77788,https://openalex.org/W2781611162,2018.0,32,"[https://openalex.org/A5052035076, https://ope..."
77841,https://openalex.org/W2095481161,2010.0,115,"[https://openalex.org/A5070641581, https://ope..."
78385,https://openalex.org/W1851160068,2013.0,61,"[https://openalex.org/A5083523038, https://ope..."
78443,https://openalex.org/W2029931724,2007.0,46,"[https://openalex.org/A5017222566, https://ope..."
78510,https://openalex.org/W1944480502,2015.0,28,"[https://openalex.org/A5011536957, https://ope..."

In [28]:
abstracts_dataset = abstracts_dataset.drop_duplicates(subset = "id")
abstracts_dataset

,id,title,abstract_index
0,https://openalex.org/W1999649023,Statistical Methods for Meta-Analysis,"{'Preface.': [0], 'Introduction.': [1], 'Data'..."
1,https://openalex.org/W2055957857,Framing as a Theory of Media Effects,"{'Research': [0], 'on': [1], 'framing': [2, 25..."
2,https://openalex.org/W3121315632,What Makes Online Content Viral?,"{'Why': [0], 'are': [1, 129], 'certain': [2], ..."
3,https://openalex.org/W2002781392,"Framing, Agenda Setting, and Priming: The Evol...","{'This': [0], 'special': [1], 'issue': [2], 'o..."
4,https://openalex.org/W2885869279,How to Do a Systematic Review: A Best Practice...,"{'Systematic': [0], 'reviews': [1, 54, 133, 15..."
...,...,...,...
81012,https://openalex.org/W4229711519,When one cause casts doubt on another: A norma...,NaN
81013,https://openalex.org/W4244918428,Thinking of Others: How Perspective Taking Cha...,"{'The': [0], 'current': [1], 'research': [2], ..."
81014,https://openalex.org/W4245271589,Debiasing,"{'This': [0], 'chapter': [1], 'contains': [2],..."
81015,https://openalex.org/W2249172038,Broaden the Decision Frame to Make Effective D...,NaN
81016,https://openalex.org/W4386888655,Individual Differences in Overconfidence and t...,NaN